version: '3.8'

services:

# This repository contains the Docker Compose setup to quickly deploy the Modern Data Stack.

#List of Services
# 1.  postgres                  - 10.0.0.30
# 3.  dagster                   - 10.0.0.28  
# 4.  dagster-daemon            - 10.0.0.27
# 5.  mongodb                   - 10.0.0.26
# 6.  opentelemetry-collector   - 10.0.0.25
# 7.  nessie                    - 10.0.0.24
# 8.  minio                     - 10.0.0.23
# 9.  minio-setup               - 10.0.0.22
# 10. dremio                    - 10.0.0.21
# 12. spark                     - 10.0.0.19
# 13. prometheus                - 10.0.0.18
# 12. grafana                   - 10.0.0.17


#Postgres is being leveraged for the dagster (dagster and dagster daemon) metadata and also for other testing purposes
# 4 db's are created dagster, fnb, mydb, postgres (this is terces)
  postgres:
    image: postgres:13
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: "dagster"
      POSTGRES_PASSWORD: "dagster"
      POSTGRES_DB: "dagster"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dagster"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      terces:
        ipv4_address: 10.0.0.30

  #opentelemetry-collector
  opentelemetry-collector:
    image: otel/opentelemetry-collector:latest
    ports:
      - "4317:4317"
    container_name: opentelemetry-collector
    hostname: opentelemetry-collector
    networks:
      terces:
        ipv4_address: 10.0.0.25
    command: ["--config", "/etc/otel-collector-config.yml"]
    volumes:
      - ./opentelemetry-collector/data/otel-collector-config.yml:/etc/otel-collector-config.yml


  # Dremio
  dremio:
    image: dremio/dremio-oss:24.2
    ports:
      - 9047:9047
      - 31010:31010
      - 32010:32010
    container_name: dremio
    hostname: dremio
    environment:
      - DREMIO_JAVA_SERVER_HEAP_MAX=4G
      - DREMIO_JAVA_SERVER_HEAP_MIN=4G
      - DREMIO_JAVA_SERVER_EXTRA_OPTS=-Dpaths.dist=file:///opt/dremio/data/dist
    volumes:
      - dremio_data:/opt/dremio/data
      - dremio_log:/opt/dremio/log
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9047 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      terces:
        ipv4_address: 10.0.0.21

volumes:
  postgres_data:
  minio_data:
  mongodb_data:
  dremio_data:
  dremio_log:
  spark_data:
    driver: local

networks:
  terces:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16
