global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['10.0.0.31:9187']  # IP address of postgres_exporter

  - job_name: 'dremio'
    static_configs:
      - targets: ['10.0.0.21:9091']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['10.0.0.25:8890']
